.TH "bug" 3 "EASY-CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
.PP


.PP
.IP "\fBMember \fBMyLibrary::Example::test\fP (const std::string &test)
.IP "" 1c
example bug 

.PP
.IP "\fBMember \fBMyLibrary::SubclassExample< TemplatedClass >::virtualfunc\fP () override
.IP "" 1c
second bug 

.PP

