.TH "MyLibrary::SecondExample" 3 "EASY-CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyLibrary::SecondExample
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <example\&.hpp>\fP
.SH "Detailed Description"
.PP 
Definition at line \fB164\fP of file \fBexample\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EASY-CPP from the source code\&.
