.TH "MyLibrary" 3 "EASY-CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyLibrary
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExample\fP"
.br
.RI "\fBExample\fP class to demonstrate the features of the custom CSS\&. "
.ti -1c
.RI "class \fBSecondExample\fP"
.br
.ti -1c
.RI "class \fBSubclassExample\fP"
.br
.RI "some subclass "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBColor\fP { \fBred\fP = 1, \fBgreen\fP = 2, \fBblue\fP = 3 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMyLibrary::Color\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIred \fP
.TP
\f(BIgreen \fP
.TP
\f(BIblue \fP
.PP
Definition at line \fB6\fP of file \fBexample\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EASY-CPP from the source code\&.
