.TH "Stopwatch" 3 "EASY-CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stopwatch
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <EASY\-CPP\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStopwatch\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "double \fBelapsed_seconds\fP () const"
.br
.ti -1c
.RI "long long \fBelapsed_ms\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB157\fP of file \fBEASY\-CPP\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Stopwatch::Stopwatch ()\fR [inline]\fP"

.PP
Definition at line \fB160\fP of file \fBEASY\-CPP\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "long long Stopwatch::elapsed_ms () const\fR [nodiscard]\fP"

.PP
Definition at line \fB652\fP of file \fBEASY\-CPP\&.h\fP\&.
.SS "double Stopwatch::elapsed_seconds () const\fR [nodiscard]\fP"

.PP
Definition at line \fB646\fP of file \fBEASY\-CPP\&.h\fP\&.
.SS "void Stopwatch::start ()\fR [inline]\fP"

.PP
Definition at line \fB161\fP of file \fBEASY\-CPP\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EASY-CPP from the source code\&.
