.TH "docs/doxygen-awesome-css-2.4.2/include/MyLibrary/subclass-example.hpp" 3 "EASY-CPP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
docs/doxygen-awesome-css-2.4.2/include/MyLibrary/subclass-example.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include 'example\&.hpp'\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyLibrary::SubclassExample< TemplatedClass >\fP"
.br
.RI "some subclass "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMyLibrary\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EASY-CPP from the source code\&.
